# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(702, 454)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbUserName = QtWidgets.QLabel(Dialog)
        self.lbUserName.setObjectName("lbUserName")
        self.horizontalLayout.addWidget(self.lbUserName)
        self.leUserName = QtWidgets.QLineEdit(Dialog)
        self.leUserName.setObjectName("leUserName")
        self.horizontalLayout.addWidget(self.leUserName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbPassword = QtWidgets.QLabel(Dialog)
        self.lbPassword.setObjectName("lbPassword")
        self.horizontalLayout_2.addWidget(self.lbPassword)
        self.lePassword = QtWidgets.QLineEdit(Dialog)
        self.lePassword.setObjectName("lePassword")
        self.horizontalLayout_2.addWidget(self.lePassword)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lbConnectionStatus = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbConnectionStatus.sizePolicy().hasHeightForWidth())
        self.lbConnectionStatus.setSizePolicy(sizePolicy)
        self.lbConnectionStatus.setObjectName("lbConnectionStatus")
        self.horizontalLayout_3.addWidget(self.lbConnectionStatus)
        self.btnConnect = QtWidgets.QPushButton(Dialog)
        self.btnConnect.setObjectName("btnConnect")
        self.horizontalLayout_3.addWidget(self.btnConnect)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lvProjects = QtWidgets.QListWidget(Dialog)
        self.lvProjects.setObjectName("lvProjects")
        self.verticalLayout_2.addWidget(self.lvProjects)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.lvUsers = QtWidgets.QListWidget(Dialog)
        self.lvUsers.setObjectName("lvUsers")
        self.verticalLayout_3.addWidget(self.lvUsers)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(self.leUserName.clear)
        self.pushButton.clicked.connect(self.lePassword.clear)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbUserName.setText(_translate("Dialog", "User Name:"))
        self.lbPassword.setText(_translate("Dialog", "Password :"))
        self.lbConnectionStatus.setText(_translate("Dialog", "TextLabel"))
        self.btnConnect.setText(_translate("Dialog", "Connect"))
        self.pushButton.setText(_translate("Dialog", "Clear"))
        self.label.setText(_translate("Dialog", "Projects"))
        self.label_2.setText(_translate("Dialog", "Users"))
